# Pin a Specific base image version for stability
# Use debian for easier build utilities
# Use Separate stage for building the application
FROM node:25.7.0-bullseye AS build

# Set a working directory
WORKDIR /usr/src/app

# Copy only those files needed to install dependencies(better layer caching)
COPY package*.json ./

RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Application
RUN npm run build

FROM nginx:alpine

# Copy nginx configuration file to serve the static files from the build stage
# Use COPY --link to create a hard link instead of copying the file, 
# which can save space and speed up the build process
COPY --link nginx.conf /etc/nginx/conf.d/default.conf

# Copy the build artifact(/dist) from the build stage to nginx's html directory
COPY --link --from=build /usr/src/app/dist /usr/share/nginx/html

# No need to specify CMD as nginx image already has a default CMD["nginx", "-g", "daemon off;"] to start nginx server