# Pin a Specific base image version for stability
# Use slim version of node to reduce image size
FROM node:19.6-bullseye-slim

# Set a working directory
WORKDIR /usr/src/app

# Copy only those files needed to install dependencies(better layer caching)
COPY package*.json ./

RUN npm install

# Copy the rest of the application code
COPY . .

CMD ["npm","run","dev"]