# Pin a Specific base image version for stability
# Use slim version of node to reduce image size
FROM node:19.6-bullseye-slim

# set node environment to production
ENV NODE_ENV=production

# Set a working directory
WORKDIR /usr/src/app

# Copy only those files needed to install dependencies(better layer caching)
COPY package*.json ./

# Install only production dependencies
RUN npm ci --only=production

# Copy the rest of the application code
COPY . .

# Write the command to run the application with respect to production environment
CMD ["node","src/index.js"]